from django import forms

class EgressoForm(forms.Form):
    email =             forms.EmailField(max_length=100, widget=forms.TextInput(attrs={'class':'form-control'}), label='*Email:')
    first_name =        forms.CharField(max_length=100, widget=forms.TextInput(attrs={'class':'form-control'}), label='*Nome:')
    last_name =         forms.CharField(max_length=100,widget=forms.TextInput(attrs={'class':'form-control'}), label='*Sobrenome:')
    sexo =              forms.ChoiceField(choices=[('M', 'Masculino'), ('F', 'Feminino')])
    password1 =         forms.CharField(widget=forms.PasswordInput(attrs={'class':'form-control'}), label='*Senha:')
    password2 =         forms.CharField(widget=forms.PasswordInput(attrs={'class':'form-control'}), label='*Repita a senha:')
    telefone=           forms.CharField(max_length=100, widget=forms.TextInput(attrs={'class':'form-control'}), label='*Contato:')
    lattes=             forms.URLField(max_length=100, widget=forms.TextInput(attrs={'class':'form-control'}), label='Link do Curriculo Lattes:', required=False)
    areaDeAtuacao =     forms.CharField(max_length=100, widget=forms.TextInput(attrs={'class':'form-control'}), label='Area de Atuacao', required=False)
    consultor =         forms.BooleanField(label='Consultor?', required=False)
    empreendedor =      forms.BooleanField(label='Empreendedor?', required=False)
    rua =               forms.CharField(max_length=100, widget=forms.TextInput(attrs={'class':'form-control'}), label='Rua:', required=False)
    cep =               forms.CharField(max_length=8, widget=forms.TextInput(attrs={'class':'form-control'}), label='CEP:', required=False)
    bairro =            forms.CharField(max_length=100, widget=forms.TextInput(attrs={'class':'form-control'}), label='Bairro:', required=False)
    cidade =            forms.CharField(max_length=100, widget=forms.TextInput(attrs={'class':'form-control'}), label='Cidade:', required=False)
    estado =            forms.CharField(max_length=100, widget=forms.TextInput(attrs={'class':'form-control'}), label='Estado:', required=False)
    foto =              forms.ImageField(required=False)